### ISSUE TITLE
Change package name and namespace

### ISSUE THREAD

**Issue by dbalabka** [ecentria/JsonApiBundle#23]
Due to `2.0` version will not contain the original source we may change the package name, namespace and make a hard fork. It is better to do such BC break in `2.0` version.

1. Rename `Mongo` to `Ecentria`
2. Move serializer library classes from `*\Bundle\*` to `*\Library\*` (or `*\Component\*` ?) namespace, because it might be used as a separate library
3. Setup [deptrac](https://github.com/sensiolabs-de/deptrac) to control bundle and library boundaries 

Depfile example (works with current structure)
```yaml
paths:
  - ./
layers:
  - name: Bundle
    collectors:
      - type: className
        regex: Mango\\Bundle\\JsonApiBundle\\(?!Serializer)
  - name: Library
    collectors:
      - type: className
        regex: Mango\\Bundle\\JsonApiBundle\\Serializer.*
ruleset:
  # Bundle can depend on library
  Bundle:
    - Library
  # Serializer library should be independent
  Library: ~

```
Current violations:
```text
Mango\Bundle\JsonApiBundle\Serializer\Accessor\DefaultAccessorStrategy::14 must not depend on Mango\Bundle\JsonApiBundle\Util\Model\AffectedPropertiesAwareInterface (Library on Bundle)
Mango\Bundle\JsonApiBundle\Serializer\Accessor\DefaultAccessorStrategy::44 must not depend on Mango\Bundle\JsonApiBundle\Util\Model\AffectedPropertiesAwareInterface (Library on Bundle)
Mango\Bundle\JsonApiBundle\Serializer\Handler\AbstractPaginationHandler::15 must not depend on Mango\Bundle\JsonApiBundle\Representation\PaginatedRepresentation (Library on Bundle)
Mango\Bundle\JsonApiBundle\Serializer\Handler\AbstractPaginationHandler::86 must not depend on Mango\Bundle\JsonApiBundle\Representation\PaginatedRepresentation (Library on Bundle)
Mango\Bundle\JsonApiBundle\Serializer\Handler\ArrayCollectionHandler::14 must not depend on Mango\Bundle\JsonApiBundle\MangoJsonApiBundle (Library on Bundle)
Mango\Bundle\JsonApiBundle\Serializer\Handler\ConstraintViolationHandler::15 must not depend on Mango\Bundle\JsonApiBundle\MangoJsonApiBundle (Library on Bundle)
Mango\Bundle\JsonApiBundle\Serializer\Handler\DateHandler::15 must not depend on Mango\Bundle\JsonApiBundle\MangoJsonApiBundle (Library on Bundle)
Mango\Bundle\JsonApiBundle\Serializer\Handler\ExceptionHandler::15 must not depend on Mango\Bundle\JsonApiBundle\MangoJsonApiBundle (Library on Bundle)
Mango\Bundle\JsonApiBundle\Serializer\Handler\PagerfantaHandler::12 must not depend on Mango\Bundle\JsonApiBundle\Representation\PaginatedRepresentation (Library on Bundle)
Mango\Bundle\JsonApiBundle\Serializer\Handler\PagerfantaHandler::51 must not depend on Mango\Bundle\JsonApiBundle\Representation\PaginatedRepresentation (Library on Bundle)
Mango\Bundle\JsonApiBundle\Serializer\JsonApiSerializationVisitor::18 must not depend on Mango\Bundle\JsonApiBundle\Configuration\Metadata\ClassMetadata (Library on Bundle)
Mango\Bundle\JsonApiBundle\Serializer\JsonApiSerializationVisitor::19 must not depend on Mango\Bundle\JsonApiBundle\EventListener\Serializer\JsonEventSubscriber (Library on Bundle)

```
